using Owl.Models.Variables;

namespace Owl.Services.VariableResolvers;

public partial class VariableResolverFactory : IVariableResolverFactory
{
	// TODO: Remove this as this is now dynamically generated by SourceGen in /Owl.Generators
	// private readonly IRequestNodeRepository _requestNodeRepository;
	// private readonly IRequestNodeState _requestNodeState;
	//
	// public VariableResolverFactory(IRequestNodeRepository requestNodeRepository, IRequestNodeState requestNodeState)
	// {
	// 	_requestNodeRepository = requestNodeRepository;
	// 	_requestNodeState = requestNodeState;
	// }

	public IVariableResolver GetResolver(IVariable variable)
	{
		// FIXME: This is just a workaround to compile until I figure out the compilation error with source-gen
		// return new StaticVariableResolver(variable as StaticVariable);
		return SourceGenMapping(variable);
	}
}
