using Owl.Models.Variables;

namespace Owl.Services.VariableResolvers;


public partial class VariableResolverFactory : IVariableResolverFactory
{
	// TODO: Remove this as this is now dynamically generated by SourceGen in /Owl.Generators
	// private readonly IRequestNodeRepository _requestNodeRepository;
	// private readonly IRequestNodeState _requestNodeState;
	//
	// public VariableResolverFactory(IRequestNodeRepository requestNodeRepository, IRequestNodeState requestNodeState)
	// {
	// 	_requestNodeRepository = requestNodeRepository;
	// 	_requestNodeState = requestNodeState;
	// }

	public IVariableResolver GetResolver(IVariable variable)
	{
		// Use generated source code for mapping
		return _getResolver(variable);
	}
}
